kind: pipeline
type: kubernetes
name: build-and-test

trigger:
  events:
  - pull_request
  - push
  - cron

steps:
- name: Cargo
  image: rust:1.55.0-bullseye
  resources:
    limits:
      cpu: 6000
  commands:
  - cargo build
  - cargo test

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Twinsight Login Server - build-and-test
  when:
    status: [ failure ]
    event:
    - push
    - cron
    branch: master
